### PR TITLE
Use @else if instead of @elseif

### PR DESCRIPTION
**Pull request by aaitmouloud**
Fixes issue #103.

### CODE REVIEW

**Comment by Yakoot** [comment]
fixed here [compass-mixins-fixed](https://github.com/Yakoot/compass-mixins-fixed)

**Comment by GMaxera** [comment]
Is this library still maintained ? If no ... what are my alternatives ?
Thanks.

**Comment by Yakoot** [comment]
> Is this library still maintained ? If no ... what are my alternatives ?
> Thanks.

if you want just elseif fix - use my fork https://github.com/Yakoot/compass-mixins-fixed

**Comment by GMaxera** [comment]
> > Is this library still maintained ? If no ... what are my alternatives ?
> > Thanks.
> 
> if you want just elseif fix - use my fork https://github.com/Yakoot/compass-mixins-fixed

It doesn't seem that the latest release in your fork include the fix :-(

**Comment by Yakoot** [comment]
> > > Is this library still maintained ? If no ... what are my alternatives ?
> > > Thanks.
> > 
> > 
> > if you want just elseif fix - use my fork https://github.com/Yakoot/compass-mixins-fixed
> 
> It doesn't seem that the latest release in your fork include the fix :-(

sorry, i forgot to create a release)
but be sure that the fix is included, just install compass-mixins-fixed from npm

**Comment by Igosuki** [comment]
Fixed in #114

**Pull request closed without merging**
